---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tic-tac-toe
  labels:

    opentelemetry.io/name: tic-tac-toe
    app.kubernetes.io/instance: tic-tac-toe
    app.kubernetes.io/name: tic-tac-toe
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: tic-tac-toe